print ('Эта программа считывает целое число, и печатает его предыдущее, и следущее значение')
x = int(input('Введите целове число: ')) 
print ('The next number for the number ', x , ' is ', x + 1, '.')
print ('The previous number for the number ', x , ' is ' , x - 1 , '.')
input ('Введите Enter чтобы закончить.')
